[FIX 2 Errors]
Fixed 2 errors due to package update in SQLAlchemy=1.4.15 and not
compatible to sqlite

- Closing connections too early problem: Please see this file
  https://github.com/kennethreitz/records/pull/190/files
- AttributeError: 'RMKeyView' object has no attribute 'index': Since the
  'RMKeyView' is no longer works as list type, it has no attribute like
  'index' and 'count'. So change the type cast as list when calling
  'self.keys()' at 'Record.__getitem__' function in 'records.py' file.